/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as InstagramCallbackRouteImport } from './routes/instagram.callback'
import { Route as DashboardPerfilRouteImport } from './routes/_dashboard.perfil'
import { Route as DashboardGaleriaRouteImport } from './routes/_dashboard.galeria'
import { Route as DashboardCalendarioRouteImport } from './routes/_dashboard.calendario'
import { Route as DashboardAutomaticoRouteImport } from './routes/_dashboard.automatico'
import { Route as ApiIntegrationsInstagramCallbackRouteImport } from './routes/api.integrations.instagram.callback'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const InstagramCallbackRoute = InstagramCallbackRouteImport.update({
  id: '/instagram/callback',
  path: '/instagram/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPerfilRoute = DashboardPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGaleriaRoute = DashboardGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarioRoute = DashboardCalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAutomaticoRoute = DashboardAutomaticoRouteImport.update({
  id: '/automatico',
  path: '/automatico',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiIntegrationsInstagramCallbackRoute =
  ApiIntegrationsInstagramCallbackRouteImport.update({
    id: '/api/integrations/instagram/callback',
    path: '/api/integrations/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/automatico': typeof DashboardAutomaticoRoute
  '/calendario': typeof DashboardCalendarioRoute
  '/galeria': typeof DashboardGaleriaRoute
  '/perfil': typeof DashboardPerfilRoute
  '/instagram/callback': typeof InstagramCallbackRoute
  '/api/integrations/instagram/callback': typeof ApiIntegrationsInstagramCallbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/automatico': typeof DashboardAutomaticoRoute
  '/calendario': typeof DashboardCalendarioRoute
  '/galeria': typeof DashboardGaleriaRoute
  '/perfil': typeof DashboardPerfilRoute
  '/instagram/callback': typeof InstagramCallbackRoute
  '/': typeof DashboardIndexRoute
  '/api/integrations/instagram/callback': typeof ApiIntegrationsInstagramCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_dashboard/automatico': typeof DashboardAutomaticoRoute
  '/_dashboard/calendario': typeof DashboardCalendarioRoute
  '/_dashboard/galeria': typeof DashboardGaleriaRoute
  '/_dashboard/perfil': typeof DashboardPerfilRoute
  '/instagram/callback': typeof InstagramCallbackRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/api/integrations/instagram/callback': typeof ApiIntegrationsInstagramCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/sso-callback'
    | '/automatico'
    | '/calendario'
    | '/galeria'
    | '/perfil'
    | '/instagram/callback'
    | '/api/integrations/instagram/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/sso-callback'
    | '/automatico'
    | '/calendario'
    | '/galeria'
    | '/perfil'
    | '/instagram/callback'
    | '/'
    | '/api/integrations/instagram/callback'
  id:
    | '__root__'
    | '/_dashboard'
    | '/login'
    | '/sso-callback'
    | '/_dashboard/automatico'
    | '/_dashboard/calendario'
    | '/_dashboard/galeria'
    | '/_dashboard/perfil'
    | '/instagram/callback'
    | '/_dashboard/'
    | '/api/integrations/instagram/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  InstagramCallbackRoute: typeof InstagramCallbackRoute
  ApiIntegrationsInstagramCallbackRoute: typeof ApiIntegrationsInstagramCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/instagram/callback': {
      id: '/instagram/callback'
      path: '/instagram/callback'
      fullPath: '/instagram/callback'
      preLoaderRoute: typeof InstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/perfil': {
      id: '/_dashboard/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof DashboardPerfilRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/galeria': {
      id: '/_dashboard/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof DashboardGaleriaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/calendario': {
      id: '/_dashboard/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof DashboardCalendarioRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/automatico': {
      id: '/_dashboard/automatico'
      path: '/automatico'
      fullPath: '/automatico'
      preLoaderRoute: typeof DashboardAutomaticoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/integrations/instagram/callback': {
      id: '/api/integrations/instagram/callback'
      path: '/api/integrations/instagram/callback'
      fullPath: '/api/integrations/instagram/callback'
      preLoaderRoute: typeof ApiIntegrationsInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAutomaticoRoute: typeof DashboardAutomaticoRoute
  DashboardCalendarioRoute: typeof DashboardCalendarioRoute
  DashboardGaleriaRoute: typeof DashboardGaleriaRoute
  DashboardPerfilRoute: typeof DashboardPerfilRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAutomaticoRoute: DashboardAutomaticoRoute,
  DashboardCalendarioRoute: DashboardCalendarioRoute,
  DashboardGaleriaRoute: DashboardGaleriaRoute,
  DashboardPerfilRoute: DashboardPerfilRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  InstagramCallbackRoute: InstagramCallbackRoute,
  ApiIntegrationsInstagramCallbackRoute: ApiIntegrationsInstagramCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
