/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InstagramRouteImport } from './routes/instagram'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstagramCallbackRouteImport } from './routes/instagram.callback'
import { Route as ApiIntegrationsInstagramCallbackRouteImport } from './routes/api.integrations.instagram.callback'

const InstagramRoute = InstagramRouteImport.update({
  id: '/instagram',
  path: '/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstagramCallbackRoute = InstagramCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => InstagramRoute,
} as any)
const ApiIntegrationsInstagramCallbackRoute =
  ApiIntegrationsInstagramCallbackRouteImport.update({
    id: '/api/integrations/instagram/callback',
    path: '/api/integrations/instagram/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/billing': typeof BillingRoute
  '/instagram': typeof InstagramRouteWithChildren
  '/instagram/callback': typeof InstagramCallbackRoute
  '/api/integrations/instagram/callback': typeof ApiIntegrationsInstagramCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/billing': typeof BillingRoute
  '/instagram': typeof InstagramRouteWithChildren
  '/instagram/callback': typeof InstagramCallbackRoute
  '/api/integrations/instagram/callback': typeof ApiIntegrationsInstagramCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/billing': typeof BillingRoute
  '/instagram': typeof InstagramRouteWithChildren
  '/instagram/callback': typeof InstagramCallbackRoute
  '/api/integrations/instagram/callback': typeof ApiIntegrationsInstagramCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/billing'
    | '/instagram'
    | '/instagram/callback'
    | '/api/integrations/instagram/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/billing'
    | '/instagram'
    | '/instagram/callback'
    | '/api/integrations/instagram/callback'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/billing'
    | '/instagram'
    | '/instagram/callback'
    | '/api/integrations/instagram/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  BillingRoute: typeof BillingRoute
  InstagramRoute: typeof InstagramRouteWithChildren
  ApiIntegrationsInstagramCallbackRoute: typeof ApiIntegrationsInstagramCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/instagram': {
      id: '/instagram'
      path: '/instagram'
      fullPath: '/instagram'
      preLoaderRoute: typeof InstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instagram/callback': {
      id: '/instagram/callback'
      path: '/callback'
      fullPath: '/instagram/callback'
      preLoaderRoute: typeof InstagramCallbackRouteImport
      parentRoute: typeof InstagramRoute
    }
    '/api/integrations/instagram/callback': {
      id: '/api/integrations/instagram/callback'
      path: '/api/integrations/instagram/callback'
      fullPath: '/api/integrations/instagram/callback'
      preLoaderRoute: typeof ApiIntegrationsInstagramCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InstagramRouteChildren {
  InstagramCallbackRoute: typeof InstagramCallbackRoute
}

const InstagramRouteChildren: InstagramRouteChildren = {
  InstagramCallbackRoute: InstagramCallbackRoute,
}

const InstagramRouteWithChildren = InstagramRoute._addFileChildren(
  InstagramRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  BillingRoute: BillingRoute,
  InstagramRoute: InstagramRouteWithChildren,
  ApiIntegrationsInstagramCallbackRoute: ApiIntegrationsInstagramCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
